#!/bin/bash

readargs() {
  while [ "$#" -gt 0 ] ; do
    case "$1" in
       -c)
        if [ "$2" ] ; then
          codename="$2"
          shift ; shift
        else
          echo "Missing a value for $1."
          echo
          shift
          usage
exit
        fi
      ;;
      *)
        echo "Unknown option or argument $1."
        echo
        shift
        usage
      exit
      ;;
    esac
  done
}

#  BEGIN THE PROGRAM
readargs "$@"
name=xbmc

rm -rf ${name}-${codename}/
rm -f ${name}-${codename}.tar.gz
git clone --depth 1 https://github.com/xbmc/xbmc.git ${name}-${codename} 
pushd ${name}-${codename}
git checkout --force 18.2-Leia 
echo "You are in Commit: $( git rev-parse HEAD )"
git submodule init && git submodule update
popd
tar -cvzf ${name}-${codename}.tar.gz ${name}-${codename}

